application:
    rest:
        context-path: /api
        allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200, http://localhost:4201}
        secret-key: ${key:mykey123456789abcdmykey123456789abcdmykey123456789abcd}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: phoneshop_piti
    password: piti123
  jpa: 
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect = org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
      
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml   
    
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
       
  resources:
    web:
      resources:
        static-locations:
          classpath:
            /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  

 
      
      
